// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mbiHjzMQCpqhqVTzdSljGnjdaYPDPDk',
    appId: '1:788431920261:web:086f18a5c8337bf54fddec',
    messagingSenderId: '788431920261',
    projectId: 'ecommerce-abbd3',
    authDomain: 'ecommerce-abbd3.firebaseapp.com',
    storageBucket: 'ecommerce-abbd3.appspot.com',
    measurementId: 'G-SL2SYXBY6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEc92bxeWu9HYWIicttPLtUzVyAZI6ZpU',
    appId: '1:788431920261:android:57d27889fc7f5a354fddec',
    messagingSenderId: '788431920261',
    projectId: 'ecommerce-abbd3',
    storageBucket: 'ecommerce-abbd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpFJlkAy7VXGQM_cbsNdGX0NtE6rhaA8',
    appId: '1:788431920261:ios:f5e02ea0fdebf92f4fddec',
    messagingSenderId: '788431920261',
    projectId: 'ecommerce-abbd3',
    storageBucket: 'ecommerce-abbd3.appspot.com',
    androidClientId: '788431920261-u145himr4h5sn3p2agql7s7u51uhvmln.apps.googleusercontent.com',
    iosClientId: '788431920261-6ujd3rnljd2obbmksqbh77oa64c4cbe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sStore',
  );
}
